^(?=\d+ >>.*\n?).*$|^(?=(\d+\s))..

In [2]:
#1
import torch
import torch.nn as nn

data = torch.Tensor ([1, 2, 3])
softmax_function = nn.Softmax(dim =0)
output = softmax_function(data)
assert round (output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [8]:
#2

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        e_x = torch.exp(x)
        return e_x / e_x.sum()

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [12]:
#3

class MySoftmax(nn.Module):
    def __init__(self):
        super(MySoftmax, self).__init__()

    def forward(self, x):
            e_x = torch.exp(x)
            return e_x / e_x.sum()

data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output


tensor([0., 0., nan])

In [14]:
class SoftmaxStable ( nn . Module ):
    def __init__ ( self ) :
        super ().__init__()

    def forward ( self , x ) :
        x_max = torch .max(x , dim =0 , keepdims = True )
        x_exp = torch . exp ( x - x_max . values )
        partition = x_exp .sum (0 , keepdims = True )
        return x_exp / partition

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])